apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  TEST_ENV: test

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: ["env"]
      envFrom:
        - configMapRef:
            name: test-config # ConfigMap の metadata.name と同一にする
