apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  usernaem: YWRtaW4K # admin
  password: MTIzNAo= # 1234

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: ["env"]
      envFrom:
        - secretRef:
            name: mysecret # Secret の metadata.name と同一にする
