apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  data.csv: bmFtZSxhZ2UKbmFrYSwxCnRhbmFrYSwyCg==

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: secret # volumes.name と同一
          mountPath: "/datadir"
          readOnly: true
  volumes:
    - name: secret
      secret:
        secretName: mysecret # ConfigMap の metadata.name と同一
